---
title: "Final Project 2"
author: "Chloe Huang"
date: "7/16/2021"
output: 
  html_document: 
    keep_md: TRUE
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
library(tidyverse)
library(ggmap)
```


# Load the college dataset
```{r}
college <- read_csv('http://672258.youcanlearnit.net/college.csv')
college <- college %>%
  mutate(state=as.factor(state), region=as.factor(region),
         highest_degree=as.factor(highest_degree),
         control=as.factor(control), gender=as.factor(gender),
         loan_default_rate=as.numeric(loan_default_rate))

#view(college)

# Load state information
states <- map_data("state")

```

```{r}

# Remove Alaska and Hawaii
college <- college %>%
  filter(state!="HI" & state!="AK")

# plot the map
ggplot(states) +
  geom_polygon(mapping=aes(x=long,y=lat,group=group), color="grey", fill="beige") +
  coord_map() +
  theme(plot.background=element_blank(), 
        panel.background = element_blank(), 
        axis.title=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank()) +
  geom_point(data=college, mapping=aes(x=lon, y=lat, color = control, size = undergrads))
```

```{r}
tx <-map_data(map="county", region = "Texas")


college <- college %>%
  # filter(admission_rate > 0.5) %>%
  filter(state == "TX")


ggplot(tx) +
  geom_polygon(mapping=aes(x=long,y=lat,group=group), color="grey", fill="beige") +
  coord_map() +
  theme(plot.background=element_blank(), 
        panel.background = element_blank(), 
        axis.title=element_blank(), 
        axis.ticks=element_blank(), 
        axis.text=element_blank()) +
  geom_point(data=college, mapping=aes(x=lon, y=lat, color = control, size = undergrads))

```