---
title: "Task 6 Dplyr and Gapminder"
author: "Chloe Huang"
date: "6/7/2021"
output: 
  html_document:
    keep_md: TRUE
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(gapminder)
```


```{r}
# Filter out Kuwait
gap <- gapminder %>%
  filter(country != "Kuwait")

weighted.mean <- gap %>%
  arrange(desc(gdpPercap)) %>%
  mutate(wtmean = weighted.mean(gdpPercap, pop))

```


# Chart 1 Recreate

```{r}
chart <- gap %>%
  group_by(continent, year) %>%
  mutate(wtmean = weighted.mean(gdpPercap, pop)) %>%
  mutate(pop2 = pop/10000)

chart %>%
ggplot(aes(x= year, y= gdpPercap)) +
  geom_point(aes(color = continent, size = pop2)) +
  theme_bw() +
  scale_size_continuous(breaks = c(10000, 20000, 30000)) +
  labs(y = 'GDP per capita', x = 'Year', title = 'Population Growth by Continent Over Time', color = 'Continent', size = 'Population (100k)') +
  geom_line(aes(group = country, color = continent)) +
  geom_line(aes(x = year, y = wtmean)) +
  geom_point(aes(x = year, y = wtmean)) +
  facet_grid(. ~ continent)
```




# Chart 2 Africa, Americas and Asia expectancy

```{r}
table(gapminder$continent)
```


```{r}
# Get data for Africa, Americas and Asia
gapminder %>% 
  filter(continent %in% c("Africa","Asia","Americas"))
```

```{r}
# 1. Find the countries who has the greatest and smallest change from these 3 continents


# calculate the changes
my_countries <- gapminder %>% 
  group_by(country) %>% 
  mutate(lifeExp_1952 = lifeExp[year == 1952],
         lifeExp_2007 = lifeExp[year == 2007],
         lifeExp_change = lifeExp_2007 - lifeExp_1952) %>% 
  distinct(continent, country, lifeExp_change) %>% 
  
  # find min and max for each continent
  filter(continent %in% c("Americas","Asia","Africa")) %>% 
  group_by(continent) %>% 
  arrange(continent, lifeExp_change) %>% 
  slice(1,n())  # selects the first and last row in each group
my_countries

```
```{r}
# get the data that contains the countries we need
new_gapminder <- gapminder %>% 
  filter(country %in% my_countries$country)
```

```{r}
chart2 <- new_gapminder %>%
  ggplot(aes(x = year, y = lifeExp, color = country)) +
  geom_point(aes(size = pop/10000)) +
  geom_line()+
  theme_bw() +
  labs(y = 'Life Expectancy', x = 'Year', title = 'Life Expectancy by Country Over Time', size = 'Population Size') 
  
chart2

```
